spring.application.name=my-market-app-reactive
server.port=8080

spring.r2dbc.url=r2dbc:h2:mem:///mymarket;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.data.redis.url=redis://localhost:6379
spring.cache.redis.time-to-live=PT1M
