/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mymarketapp.reactive;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class WebfluxPracticeApplication {
    public static void main(String[] args) {
        SpringApplication.run(WebfluxPracticeApplication.class, args);
    }
}
